### ISSUE TITLE
error_messages are None and causes FATAL

### ISSUE THREAD

**Issue by servetcoskun** [sheaffej/b2#2]
Hi, I have had a lot of fun fiddling around with this library.

I am having issues running b2.launch as the two roboclaws for some reason are not sending status messages. I have successfully run them individually at full speed with the official python library for the controller. I am using 2x15A but either the front or rear node keeps crashing. I am suspecting it is the length of my USB-microUSB cables or something wrong with the clock on my Raspberry Pi. I am running Ubuquity Robotics OS and have not done anything to the original b2 library. Here is the error message:

`[FATAL] [1590585869.377846]: Unhandled exeption...printing stack trace then shutting down node
[FATAL] [1590585869.382410]: Traceback (most recent call last):
  File "/home/ubuntu/claw/src/roboclaw_driver/nodes/roboclaw_node.py", line 245, in <module>
    node.run(loop_hz=loop_hz, deadman_secs=DEFAULT_DEADMAN_SEC)
  File "/home/ubuntu/claw/src/roboclaw_driver/nodes/roboclaw_node.py", line 103, in run
    for error in stats.error_messages:
AttributeError: 'NoneType' object has no attribute 'error_messages'
`

**Comment by servetcoskun** [comment]
Going a little deeper it seems I start losing encoder counts if I try to run motors on both roboclaws at the same time, but running each roboclaw without the other works fine. I am using 2 USB ports from a Pi to communicate with the roboclaws.

**Comment by servetcoskun** [comment]
Further investigation seems to indicate that this is a problem with USB permissions or speed. Running two seperate roboclaws is for some reason not working on the Pi 4, could be a clock issue. Running them one by one seems to work fine.

**Comment by servetcoskun** [comment]
Was able to make it work on Raspberry Pi 3 B+ by replacing the microUSB-USB cable, it still does not work on the Raspberry Pi 4 unfortunately.
